# Generated by Django 4.0.4 on 2022-06-14 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('access_original', models.BooleanField(default=False)),
                ('ability_expire', models.BooleanField(default=False)),
                ('thumbnails', models.ManyToManyField(blank=True, related_name='thumbnails', to='base.size')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tier')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('expireTime', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)])),
                ('created_time', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
