# Generated by Django 4.0.4 on 2022-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_image_created_time_alter_image_expiretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_time',
            field=models.DateTimeField(default='19.06.2022 13:22:12'),
        ),
    ]
