# Generated by Django 4.0.4 on 2022-06-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_image_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
