# Generated by Django 4.0.4 on 2022-06-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_image_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_time',
            field=models.DateField(default='19.06.2022 13:32:48'),
        ),
    ]
