# Generated by Django 4.0.4 on 2022-06-19 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_image_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 13, 39, 59, 638152)),
        ),
    ]
